const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

test("crea listas editables sin PDF y conserva las fuentes minoristas existentes", async t => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "create-list-"));
  process.env.DATA_DIR = dataDir; process.env.PORT = "0";
  process.env.SUPABASE_URL = ""; process.env.SUPABASE_SERVICE_ROLE_KEY = "";
  const { server, startServer } = require("../server");
  await startServer();
  t.after(async () => { await new Promise(resolve => server.close(resolve)); fs.rmSync(dataDir, { recursive: true, force: true }); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const call = (url, method = "GET", data) => fetch(base + url, { method, headers: { "Content-Type": "application/json" }, ...(data ? { body: JSON.stringify(data) } : {}) });
  const route = "/api/client-documents/create-price-list";
  const data = { title: "Huevos", notes: "Por maple", rows: [{ name: "MAPLE N1", price: 7000, unit: "unit" }, { name: "CAJÓN N1", price: 64000, unit: "box" }] };
  const preview = await call(route + "/preview", "POST", { data });
  assert.equal(preview.status, 200);
  assert.equal(preview.headers.get("content-type"), "application/pdf");
  assert.equal((await (await call("/api/public-client-documents")).json())["price-list"].length, 0);
  assert.equal((await call(route, "POST", { data: { ...data, rows: [] } })).status, 400);
  const uploaded = await (await call("/api/client-documents/price-list", "POST", { name: "Carne minorista.pdf", data: Buffer.from(await preview.arrayBuffer()).toString("base64") })).json();
  const created = await call(route, "POST", { data, retailEnabled: true });
  assert.equal(created.status, 201);
  const { document } = await created.json();
  assert.equal(document.name, "Huevos.pdf");
  assert.equal(document.order, 1);
  assert.equal(document.priceData, undefined);
  const saved = await (await call(`/api/client-documents/${document.id}/prices`)).json();
  assert.equal(saved.imported, false);
  assert.equal(new Set(saved.data.rows.map(row => row.id)).size, 2);
  assert.deepEqual(saved.data.rows.map(({id,...row})=>row), data.rows);
  const catalog = await (await call("/api/retail-offers/catalog")).json();
  assert(catalog.lists.find(list=>list.id===uploaded.id).enabled);
  assert(catalog.lists.find(list=>list.id===document.id).enabled);
  assert.equal(catalog.products.filter(p=>p.documentId===document.id).length, 2);
  const other = await (await call(route, "POST", { data: {...data,title:"Mayorista"}, retailEnabled: false })).json();
  assert.equal((await (await call("/api/retail-offers/catalog")).json()).lists.find(l=>l.id===other.document.id).enabled,false);
  const pdf = await call(`/api/public-client-documents/${document.id}`);
  assert.equal(Buffer.from(await pdf.arrayBuffer()).subarray(0,5).toString(),"%PDF-");
  assert.equal((await call(`/api/client-documents/${document.id}/prices`,"PUT",{data:{...saved.data,notes:"Actualizada"},revision:saved.revision})).status,200);
});
