const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { generatePricePdf } = require("../lib/price-lists");

test("importa, previsualiza, guarda, detecta conflictos y recupera PDFs sin cambiar enlaces", async t => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "price-editor-test-"));
  process.env.DATA_DIR = dataDir; process.env.PORT = "0";
  process.env.SUPABASE_URL = ""; process.env.SUPABASE_SERVICE_ROLE_KEY = "";
  const { server, startServer } = require("../server");
  await startServer();
  t.after(async () => { await new Promise(resolve => server.close(resolve)); fs.rmSync(dataDir, { recursive: true, force: true }); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const call = (url, method = "GET", data) => fetch(base + url, { method, headers: { "Content-Type": "application/json" }, ...(data ? { body: JSON.stringify(data) } : {}) });
  const originalData = { title: "Lista de prueba", notes: "Precio por kilo", rows: [{ name: "Asado", price: 10000 }] };
  const original = await generatePricePdf(originalData);
  const upload = await call("/api/client-documents/price-list", "POST", { name: "Lista.pdf", data: original.toString("base64") });
  assert.equal(upload.status, 200);
  const document = await upload.json();
  const url = `/api/client-documents/${document.id}`;
  const publicUrl = `/api/public-client-documents/${document.id}`;
  const imported = await (await call(url + "/prices")).json();
  assert.equal(imported.imported, true);
  assert.ok(imported.data.rows.some(row => row.name === "Asado" && row.price === 10000));
  const draft = { ...originalData, rows: [{ name: "Asado", price: 12000 }, { name: "Vacío", price: null }] };
  const payload = { data: draft, revision: imported.revision, reviewed: true };
  const preview = await call(url + "/preview", "POST", payload);
  assert.equal(preview.status, 200);
  assert.equal(preview.headers.get("content-type"), "application/pdf");
  assert.equal(Buffer.from(await (await call(publicUrl)).arrayBuffer()).equals(original), true);
  assert.equal((await call(url + "/prices", "PUT", { ...payload, reviewed: false })).status, 400);
  assert.equal((await call(url + "/prices", "PUT", { ...payload, data: { ...draft, rows: [{ name: "Asado", price: -5 }] } })).status, 400);
  const saves = await Promise.all([call(url + "/prices", "PUT", payload), call(url + "/prices", "PUT", payload)]);
  assert.deepEqual(saves.map(response => response.status).sort(), [200, 409]);
  const saved = await (await call(url + "/prices")).json();
  assert.equal(saved.imported, false);
  assert.deepEqual({ ...saved.data, rows: saved.data.rows.map(({ id, ...row }) => row) }, draft);
  assert.equal(new Set(saved.data.rows.map(row => row.id)).size, 2);
  const versions = await (await call(url + "/versions")).json();
  assert.equal(versions.length, 2);
  const originalVersion = versions.find(version => version.original);
  assert.equal(Buffer.from(await (await call(url + "/versions/" + encodeURIComponent(originalVersion.id))).arrayBuffer()).equals(original), true);
  const publicList = await (await call("/api/public-client-documents")).json();
  assert.equal(publicList["price-list"][0].id, document.id);
  for (const key of ["priceData", "priceHistory", "priceRevision", "storageName"]) assert.equal(key in publicList["price-list"][0], false);
  const restore = await call(url + "/restore", "POST", { versionId: originalVersion.id, revision: saved.revision });
  assert.equal(restore.status, 200);
  assert.equal(Buffer.from(await (await call(publicUrl)).arrayBuffer()).equals(original), true);
  assert.equal((await (await call(url + "/versions")).json()).length, 3);
  assert.equal((await call(url + "/restore", "POST", { versionId: "missing", revision: (await restore.json()).revision })).status, 404);
  const offers = await (await call("/api/client-documents/offers", "POST", { name: "Ofertas.pdf", data: original.toString("base64") })).json();
  assert.equal((await call(`/api/client-documents/${offers.id}/prices`)).status, 404);
  assert.equal((await call(url, "DELETE")).status, 200);
  assert.equal((await call(publicUrl)).status, 404);
  assert.equal((await call(`/api/public-client-documents/${offers.id}`)).status, 200);
});
