const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { JSDOM } = require("jsdom");

test("el editor permite seleccionar, ajustar, deshacer, editar, previsualizar y guardar", async t => {
  const html = fs.readFileSync(path.join(__dirname, "../public/index.html"), "utf8");
  const dom = new JSDOM(html, { runScripts: "outside-only", url: "http://localhost" });
  t.after(() => dom.window.close());
  const { window } = dom;
  const el = id => window.document.getElementById(id);
  let data = { title: "Lista", notes: "Precio por kilo", rows: [{ name: "Asado", price: 10000 }, { name: "Vacío", price: 1990 }, { name: "Caja", price: null }] };
  let imported = true, saved = null, previewed = null, revision = "original";
  window.dateTime = text => text;
  window.confirm = () => true;
  window.loadClientDocuments = async () => {};
  window.HTMLElement.prototype.scrollIntoView = function () {};
  el("priceEditorDialog").showModal = function () { this.open = true; };
  el("priceEditorDialog").close = function () { this.open = false; };
  window.URL.createObjectURL = () => "blob:preview";
  window.URL.revokeObjectURL = () => {};
  window.api = async (url, options = {}) => {
    if (options.method === "PUT") {
      saved = JSON.parse(options.body); data = saved.data; imported = false; revision = "saved";
      return { revision };
    }
    if (url.endsWith("/versions")) return [{ id: revision, updatedAt: "2026-09-24", original: imported, current: true }];
    return { data, revision, imported, warnings: ["Revisar"], unrecognized: ["Texto original"] };
  };
  window.fetch = async (url, options) => { previewed = JSON.parse(options.body); return { ok: true, blob: async () => new window.Blob(["%PDF-"]) }; };
  const source = fs.readFileSync(path.join(__dirname, "../public/app.js"), "utf8");
  window.eval(source.slice(source.indexOf("const priceEditor =")));
  await window.openPriceEditor({ id: "list-1" });
  assert.equal(el("priceEditorRows").children.length, 3);
  el("priceScope").value = "selected";
  el("priceEditorRows").querySelector(".price-row-selected").checked = true;
  el("priceAdjustment").value = "10"; el("priceRounding").value = "50";
  el("priceApplyAdjustment").click();
  assert.deepEqual(Array.from(el("priceEditorRows").querySelectorAll(".price-row-value"), input => input.value), ["11000", "1990", ""]);
  el("priceUndoAdjustment").click();
  assert.equal(el("priceEditorRows").querySelector(".price-row-value").value, "10000");
  el("priceScope").value = "all"; el("priceAdjustment").value = "-10"; el("priceRounding").value = "100";
  el("priceApplyAdjustment").click();
  assert.deepEqual(Array.from(el("priceEditorRows").querySelectorAll(".price-row-value"), input => input.value), ["9000", "1800", ""]);
  el("priceAddRow").click();
  const added = el("priceEditorRows").lastElementChild;
  added.querySelector(".price-row-name").value = "Nuevo producto";
  added.querySelector(".price-row-value").value = "1234.50";
  el("pricePreview").click();
  await new Promise(resolve => setImmediate(resolve));
  assert.equal(previewed.data.rows.length, 4);
  assert.equal(el("pricePreviewSection").hidden, false);
  el("priceEditorForm").dispatchEvent(new window.Event("submit", { cancelable: true }));
  assert.equal(saved, null);
  assert.match(el("priceEditorMessage").textContent, /Confirmá/);
  el("priceImportReviewed").checked = true;
  el("priceEditorForm").dispatchEvent(new window.Event("submit", { cancelable: true }));
  await new Promise(resolve => setImmediate(resolve));
  assert.equal(saved.data.rows[3].price, 1234.5);
  assert.equal(saved.reviewed, true);
  assert.equal(saved.revision, "original");
  assert.equal(el("priceImportNotice").hidden, true);
  el("priceEditorRows").lastElementChild.querySelector("button").click();
  assert.equal(el("priceEditorRows").children.length, 3);
  window.confirm = () => false;
  el("priceEditorClose").click();
  assert.equal(el("priceEditorDialog").open, true);
});
