const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
test('cotización del servidor, ofertas vencidas, cambios de precios, reintentos y preparación',async t=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cart-test-'));
  process.env.DATA_DIR=dir;process.env.PORT='0';process.env.SUPABASE_URL='';process.env.SUPABASE_SERVICE_ROLE_KEY='';
  const {server,startServer}=require('../server');await startServer();
  t.after(async()=>{await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});});
  const base=`http://127.0.0.1:${server.address().port}`;
  const call=async(p,method='GET',body)=>{const r=await fetch(base+p,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};
  const data={title:'Huevos',notes:'',rows:[{name:'MAPLE N1',price:7000,unit:'unit'}]};
  const created=(await call('/api/client-documents/create-price-list','POST',{data,retailEnabled:true})).data;
  const product=(await call('/api/retail-offers/catalog')).data.products[0];
  let offers=(await call('/api/retail-offers')).data;
  offers=(await call('/api/retail-offers','PUT',{revision:offers.revision,offers:[{productId:product.id,title:'Maples',kind:'bundle',quantity:2,unit:'unit',price:13000,active:true,startDate:'',endDate:''}]})).data;
  const policy=(await call('/api/public-order-policy?deliveryType=RETIRO')).data;
  const payload={customer:'Prueba',phone:'1155551234',saleType:'Minorista',deliveryType:'RETIRO',deliveryZone:'REGULAR',prepDate:policy.minDate,notes:'Separar bolsas',cart:[{productId:product.id,quantity:2,note:'Revisar huevos'}],estimatedAccepted:true,requestId:'cart-request-test-0001',detail:'IGNORAR TOTAL 1',orderAmount:1};
  let quote=(await call('/api/public-retail-quote','POST',payload)).data;assert.equal(quote.total,13000);
  assert.equal((await call('/api/public-orders','POST',{...payload,quoteId:quote.quoteId,estimatedAccepted:false})).status,400);
  assert.equal((await call('/api/public-orders','POST',{...payload,quoteId:'inventado'})).status,409);
  await call('/api/retail-offers','PUT',{revision:offers.revision,offers:offers.offers.map(o=>({...o,endDate:'2000-01-01'}))});
  assert.equal((await call('/api/public-retail-catalog')).data.offers.length,0);
  assert.equal((await call('/api/public-orders','POST',{...payload,quoteId:quote.quoteId})).status,409);
  quote=(await call('/api/public-retail-quote','POST',payload)).data;assert.equal(quote.total,14000);
  const submitted={...payload,quoteId:quote.quoteId};
  const results=await Promise.all([call('/api/public-orders','POST',submitted),call('/api/public-orders','POST',submitted)]);
  assert.deepEqual(results.map(r=>r.status).sort(),[200,201]);assert.equal(results[0].data.number,results[1].data.number);
  let orders=(await call('/api/orders')).data;assert.equal(orders.length,1);
  assert.equal(orders[0].orderAmount,0);assert.equal(orders[0].retailCart.total,14000);
  assert.match(orders[0].detail,/Revisar huevos/);assert.match(orders[0].detail,/TOTAL ESTIMADO/);assert.equal(orders[0].notes,'Separar bolsas');
  await call('/api/orders/'+orders[0].id,'PUT',{...orders[0],status:'Preparado',retailCart:{total:1}});
  orders=(await call('/api/orders')).data;assert.equal(orders[0].retailCart.total,14000);
  assert.equal((await call('/api/public-orders','POST',{...submitted,saleType:'Mayorista',requestId:'wholesale-request-01'})).status,400);
  const before=(await call(`/api/client-documents/${created.document.id}/prices`)).data;
  await call(`/api/client-documents/${created.document.id}/prices`,'PUT',{data:{...before.data,rows:before.data.rows.map(r=>({...r,price:8000}))},revision:before.revision});
  assert.equal((await call('/api/public-orders','POST',{...submitted,requestId:'cart-request-test-0002'})).status,409);
});
